# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
  - name: FolderPath
    type: string
    default: $(System.DefaultWorkingDirectory)
  - name: Pattern
    type: string
    default: "*.nupkg"

steps:
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@5 
    displayName: 'NuGet CodeSigning' 
    inputs: 
      ConnectedServiceName: 'EntraPowerShell ESRP CodeSign and NUGET'
      AppRegistrationClientId: '$(ODataEsrpAppRegistrationClientId)'
      AppRegistrationTenantId: '$(ODataEsrpAppRegistrationTenantId)'
      AuthAKVName: $(ODataEsrpAuthAKVName)
      AuthCertName: $(ODataEsrpAuthCertName)
      AuthSignCertName: $(ODataEsrpAuthSignCertName)
      ServiceEndpointUrl: '$(ODataEsrpServiceEndpointUrl)'
      FolderPath: ${{ parameters.FolderPath }}
      Pattern: ${{ parameters.Pattern }}
      SessionTimeout: 90
      MaxConcurrency: 25
      signConfigTYpe: 'inlineSignParams'
      inlineOperation: |
        [
            {
                "keyCode": "CP-401405",
                "operationSetCode": "NuGetSign",
                "parameters": [ ],
                "toolName": "sign",
                "toolVersion": "1.0"
            },
            {
                "keyCode": "CP-401405",
                "operationSetCode": "NuGetVerify",
                "parameters": [ ],
                "toolName": "sign",
                "toolVersion": "1.0"
            }
        ]
