# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
  - name: FolderPath
    type: string
    default: $(System.DefaultWorkingDirectory)
  - name: Pattern
    type: string
    default: "*.nupkg"

steps:
  - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@5 
    displayName: 'NuGet CodeSigning' 
    inputs: 
      ConnectedServiceName: 'EntraPowerShell ESRP CodeSign and NUGET' 
      AppRegistrationClientId: 'ce6e119c-a8c2-4744-9699-cd5389102d0d'
      AppRegistrationTenantId: '33e01921-4d64-4f8c-a055-5bdaffd5e33d' 
      AuthAKVName: 'ODataESRPKeyVault' 
      AuthCertName: 'ODataCodeSignAuth-AutoRotate'
      AuthSignCertName: 'ODataCodeSigningCert2024'
      FolderPath: ${{ parameters.FolderPath }}
      Pattern: ${{ parameters.Pattern }}
      SessionTimeout: 90 
      ServiceEndpointUrl: 'https://api.esrp.microsoft.com/api/v2' 
      MaxConcurrency: 25
      signConfigTYpe: 'inlineSignParams'
      inlineOperation: |
        [
            {
                "keyCode": "CP-401405",
                "operationSetCode": "NuGetSign",
                "parameters": [ ],
                "toolName": "sign",
                "toolVersion": "1.0"
            },
            {
                "keyCode": "CP-401405",
                "operationSetCode": "NuGetVerify",
                "parameters": [ ],
                "toolName": "sign",
                "toolVersion": "1.0"
            }
        ]
